version: '2'

services: 

  db:
    image: postgres:9.6
    volumes:
      - ./dbdata:/var/lib/postgres
    restart: always

  dbsession:
      image: postgres:9.6
      volumes:
        - ./dbdata2:/var/lib/postgres
      restart: always
    
  progdoc:
    privileged: true
    build: 
      context: .
#     dockerfile: ServerDockerfile
    restart: always
    ports: 
      - "3000:3000"
    depends_on:
      - db
      - dbsession

volumes:
  dbdata:
