version: '3'

services: 

  dbsession:
    image: postgres:9.6
    volumes:
      - dbdata2:/var/lib/postgres
    restart: always
    
  progdoc:
    build: 
      context: .
    restart: always
    volumes:
      - progdoc:/storage/progdoc/
    ports: 
      - "3000:3000"
    depends_on:
      - dbsession

volumes:
  dbdata2:
  progdoc:
