version: '3'

services:

  db:
    container_name: gestiondoc_db
    image: postgres:11
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ../config/gestionDoc/gestionDocDB.env
  dbsession:
    container_name: gestiondoc_dbsession
    env_file:
      - ../config/gestionDoc/gestionDocSession.env
  progdoc:
    build: 
      context: .
#    image: git.etsit.upm.es:4567/grupointegraciondigital/gestiondoc:stable
    depends_on:
      - db
    env_file:
      - ../config/gestionDoc/gestionDoc.env

volumes:
  dbdata:



    