version: '3'

services: 

  dbsession:
    image: postgres:11
    restart: always
    
  progdoc:
    container_name: gestiondoc_progdoc
    restart: always
    volumes:
      - progdoc:/storage/progdoc/
    ports: 
      - "3000:3000"
    depends_on:
      - dbsession

volumes:
  progdoc:
